/* Add lables to variables */
capture label variable age "CEO Age"
capture label variable allindrawn "All-in Spread Drawn"
capture label variable assetsalessweep "Asset Sale Sweep"
capture label variable at "Assets"
capture label variable atq_log "Ln(Assets)"
capture label variable block_shares_pct "% Blk Total"
capture label variable block_shares_pct_affiliated "% Blk Affiliated"
capture label variable block_shares_pct_director "% Blk Director"
capture label variable block_shares_pct_insider "% Blk Insider"
capture label variable block_shares_pct_officer "% Blk Officer"
capture label variable block_shares_pct_outsider "% Blk Outsider"
capture label variable block13_num1 "Largest Block %"
capture label variable block13_num2 "#2 Block"
capture label variable block13_num3 "#3 Block"
capture label variable block13_num4 "#4 Block"
capture label variable block13_num5 "#5 Block"
capture label variable block13_total "Block Total"
capture label variable borrowerbasetype_i "Borrower Base Type"
capture label variable CEO_Founder "Founder CEO"
capture label variable ceo_high_ownership "CEO High Ownership"
capture label variable ceo_no_unvested "CEO No Unvested Equity"
capture label variable ceo_preret "CEO Retirement Age"
capture label variable ceo_retirement_age "CEO Retirement Age"
capture label variable ceo_shrown_pct "CEO Ownership %"
capture label variable ceo_tenure "CEO Tenure"
capture label variable ceo_unvest_pct "CEO Unvested %"
capture label variable ceo_unvest_pct_excl_opts "CEO Unvested %"
capture label variable ceo_unvest_pct_log "CEO Unvested Log(%)"
capture label variable ceo_unvest_pct_log_excl_opts "CEO Unvested Log(%)"
capture label variable ceo_unvest_pct_low "CEO Low Unvested"
capture label variable ceo_unvest_pct_low_excl_opts "CEO Low Unvested"
capture label variable CG_PercInsider "% Insider (Ind.)"
capture label variable collat "Collateralized"
capture label variable credit_spread "Credit Spread"
capture label variable crsp_age "Firm Age"
capture label variable current_ratio "Current Ratio"
capture label variable dealamount "Package Amount"
capture label variable debt_mat_3 "Debt Matures > 3yr"
capture label variable debtissuancesweep "Debt Issuance Sweep"
capture label variable delist_in_7yrs "Firm Delists in 7yr"
capture label variable delist_pct_3yrs "% Industry Acquired in 3yr"
capture label variable distance "Distance"
capture label variable dividendrestrictions_i "Dividend Restriction"
capture label variable ebit_at "ROA"
capture label variable equityissuancesweep "Equity Issuance Sweep"
capture label variable excesscfsweep "Excess CF Sweep"
capture label variable facilityamt "Facility Amount"
capture label variable fdate "13-F filing date"
capture label variable goodwill "Goodwill"
capture label variable has_cic "Has CIC Clause"
capture label variable has_cmr_ever "CMR Firm"
capture label variable insuranceproceedssweep "Insurance Proceeds Sweep"
capture label variable int_exp_at "Interest Expense / Ave. Assets"
capture label variable khc_dummy "Key Human Capital"
capture label variable khc_insure "Key-person Insured"
capture label variable khc_intensity "Insurance Intensity"
capture label variable l_ebit_at "Lag ROA"
capture label variable lead_per "% Lead Allocation"
capture label variable lead_perc "% Lead Allocation"
capture label variable lev "Leverage"
capture label variable lev_book "Leverage (Book)"
capture label variable lev_mkt "Leverage (Market)"
capture label variable Leverage "Leverage"
capture label variable loanpurpose "Loan Purpose"
capture label variable log_at "Log(AT)"
capture label variable log_distance "Distance (logged)"
capture label variable log_maturity "Log(Maturity)"
capture label variable log_num_lenders "Log(# of Lenders)"
capture label variable log_roa "Log(ROA)"
capture label variable log_tangibility "Tangibility"
capture label variable maturity "Maturity"
capture label variable mtb "MtB"
capture label variable networth_to_at "Net Worth / Ave. Assets"
capture label variable new_ceo "New CEO"
capture label variable new_viol "New Covenant Violation"
capture label variable no_heir "No Heir-Apparent"
capture label variable NonCompete_low "Low NC Enforcement"
capture label variable num_fincovs "# of Financial Covenants"
capture label variable num_lenders "Number of Lenders"
capture label variable oic_at "Operating Cash Flows / Ave. Assets"
capture label variable override_restrict "Alternative CMR Clause"
capture label variable p0_oibdp_at "Operating CF"
capture label variable p0_tobinsq "Tobin's Q"
capture label variable ppricing "Performance Pricing"
capture label variable rate_dum "Rated"
capture label variable relationship "Relationship"
capture label variable restrict "CMR Clause"
capture label variable revolver "Revolver"
capture label variable roa "ROA"
capture label variable same_state "Local Lead"
capture label variable scaled_amount "Scaled Loan Amount"
capture label variable seniority_i "Senority"
capture label variable shares_ii "% Inst. Inv. Ownership"
capture label variable shares_ii_top1 "% Inst. Inv. Ownership (Top 1)"
capture label variable shares_ii_top5 "% Inst. Inv. Ownership (Top 5)"
capture label variable shrout "13-F Shares Outstanding"
capture label variable shrown_excl_opts_pct "CEO Ownership %"
capture label variable tangibility "Tangibility (Unlogged)"
capture label variable tenure "CEO Tenure"
capture label variable term_spread "Term Spread"
capture label variable top5_shrown_pct "% Shares owned by Top 5"
capture label variable TSR_1 "TSR 1 year"
capture label variable TSR_3 "TSR 3 year"
capture label variable turnover "CEO Turnover"
capture label variable turnoverq "CEO Turnover" // Quarterly
capture label variable VIXClose "VIX"
capture label variable xrd0_at "R&D / Assets"
capture label variable zscore_modified "Z-score"
capture label variable zscore_private "Z-score (prv)"
capture label variable zscore_public "Z-score (pub)"


if $writeout { // Label Variables for Latex
    capture label variable block_shares_pct "\% Blk Total"
    capture label variable block13_num1 "Largest Block \%"
    capture label variable ceo_shrown_pct "CEO Ownership \%"
    capture label variable ceo_unvest_pct "CEO Unvested \%"
    capture label variable ceo_unvest_pct_excl_opts "CEO Unvested \%"
    capture label variable ceo_unvest_pct_log "CEO Unvested Log(\%)"
    capture label variable ceo_unvest_pct_log_excl_opts "CEO Unvested Log(\%)"
    capture label variable CG_PercInsider "\% Insider (Ind.)"
    capture label variable debt_mat_3 "Debt Matures $ > $ 3yr"
    capture label variable delist_pct_3yrs "\% Industry Acquired in 3yr"
    capture label variable l_ebit_at "ROA$ _{t-1} $ "
    capture label variable lead_perc "\% Lead Allocation"
    capture label variable lead_per "\% Lead Allocation"
    capture label variable log_num_lenders "Log(\# of Lenders)"
    capture label variable log_patent_num "Log(\# Pat.)"
    capture label variable num_fincovs "\# of Financial Covenants"
    capture label variable num_ii "\# of Inst. Inv. (Norm)"
    capture label variable shares_ii "\% Inst. Inv. Ownership"
    capture label variable shares_ii_top1 "\% Inst. Inv. Ownership (Top 1)"
    capture label variable shrown_excl_opts_pct "CEO Ownership \%"
    capture label variable top5_shrown_pct "\% Shares owned by Top 5"
    capture label variable xrd0_at "R\&D / Assets"
}
